# ---------------------------------------------------------------------------
# Jetio Framework
# Website: https://jetio.org
#
# Copyright (c) 2025 Stephen Burabari Tete. All Rights Reserved.
# 
# This source code is licensed under the BSD 3-Clause license found in the
# LICENSE file in the root directory of this source tree.
#
# LinkedIn: https://www.linkedin.com/in/tete-stephen/ 
# ---------------------------------------------------------------------------

[metadata]
name = jetio
version = 1.2.3
author = Stephen Tete
author_email = cehtete@gmail.com
description = A modern, high-performance Python web framework designed to transform your SQLAlchemy models directly into fully-featured, production-ready REST APIs with minimal code. Built with asyncio, SQLAlchemy, and Pydantic.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/cehstephen/jetio
project_urls =
    Bug Tracker = https://github.com/cehstephen/jetio/issues
license_file = LICENSE
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13
    License :: OSI Approved :: BSD License
    Operating System :: OS Independent
    Development Status :: 5 - Production/Stable
    Framework :: AsyncIO
    Intended Audience :: Developers
    Topic :: Internet :: WWW/HTTP
    Topic :: Internet :: WWW/HTTP :: HTTP Servers
    Topic :: Software Development :: Libraries :: Application Frameworks
    Topic :: Software Development :: Libraries :: Python Modules
    Environment :: Web Environment
    Natural Language :: English

[options]
packages = find:
python_requires = >=3.11
install_requires =
    sqlalchemy
    pydantic[email]
    pydantic-settings
    jinja2
    uvicorn[standard]
    starlette
    python-multipart
    passlib
    PyJWT    
    jetio-auth
    aiosqlite
    
[options.packages.find]
exclude =
    tests
    tests.*
    examples
    examples.*
    
[options.extras_require]
bcrypt = passlib[bcrypt]
test =
    pytest
    pytest-asyncio
    httpx
    
